packages:
  - "apps/*"
  - "packages/*"
  - "configs/*"

catalog:
  # configs
  typescript: ^5.9.2
  eslint: ^9.39.2
  tsdown: ^0.20.1
  vite: ^7.3.1
  rimraf: ^6.1.2
  turbo: ^2.8.1

  # utils
  "@biomejs/biome": ^2.3.13
  prettier: ^3.8.1

  # testing
  vitest: ^4.0.18
  "@vitest/coverage-v8": ^4.0.18

  # types
  "@types/node": ^25.1.0
