packages:
  - "apps/*"
  - "packages/*"
  - "packages/@repo/*"
  - "configs/*"

catalog:
  # configs
  typescript: ^5.9.2
  eslint: ^9.39.2
  tsdown: ^0.20.1
  unrun: ^0.2.27

  vite: ^7.3.1
  rimraf: ^6.1.2
  turbo: ^2.8.1

  # utils
  "@biomejs/biome": ^2.3.13
  prettier: ^3.8.1
  zod: ^4.3.6

  # testing
  vitest: ^4.0.18
  "@vitest/coverage-v8": ^4.0.18

  # types
  "@types/node": ^25.1.0

  # frontend
  react: ^19.2.4
  react-dom: ^19.2.4
  lucide-react: ^0.563.0
  tailwindcss: ^4.1.18
  react-email: ^5.2.8
  "@react-email/preview-server": ^5.2.8
  "@react-email/components": ^1.0.8
  "@react-email/tailwind": ^2.0.5
  "@react-email/render": ^2.0.4

  # frontend types
  "@types/react": ^19.2.4
  "@types/react-dom": ^19.2.3
