import type { AiProvider, AiProviderModelType } from "./types.js";

export const DefaultAiModels = {
	groq: [
		{
			id: "llama-3.3-70b-versatile",
			owner: "Meta",
			contextWindowToken: 131072,
			maxCompletionToken: 32768,
			type: "text-completion",
		},
		{
			id: "llama-3.1-8b-instant",
			owner: "Meta",
			contextWindowToken: 131072,
			maxCompletionToken: 131072,
			type: "text-completion",
		},
		{
			id: "openai/gpt-oss-120b",
			owner: "OpenAI",
			contextWindowToken: 131072,
			maxCompletionToken: 65536,
			type: "text-completion",
		},
		{
			id: "openai/gpt-oss-20b",
			owner: "OpenAI",
			contextWindowToken: 131072,
			maxCompletionToken: 65536,
			type: "text-completion",
		},
	],
	openAi: [
		{
			id: "gpt-4o",
			owner: "OpenAI",
			contextWindowToken: 128000,
			maxCompletionToken: 16384,
			type: "text-completion",
		},
		{
			id: "o1",
			owner: "OpenAI",
			contextWindowToken: 200000,
			maxCompletionToken: 100000,
			type: "text-completion",
		},
		{
			id: "dall-e-3",
			owner: "OpenAI",
			contextWindowToken: 0,
			maxCompletionToken: 1,
			type: "image-generation",
		},
		{
			id: "tts-1",
			owner: "OpenAI",
			contextWindowToken: 4096,
			maxCompletionToken: 0,
			type: "audio-generation",
		},
	],
	cloudflare: [
		{
			id: "@cf/meta/llama-3.2-1b-instruct",
			owner: "Meta",
			contextWindowToken: 131072,
			maxCompletionToken: 8192,
			type: "text-completion",
		},
		{
			id: "@cf/meta/llama-3.2-3b-instruct",
			owner: "Meta",
			contextWindowToken: 131072,
			maxCompletionToken: 8192,
			type: "text-completion",
		},
		{
			id: "@cf/meta/llama-3.1-8b-instruct-fp8-fast",
			owner: "Meta",
			contextWindowToken: 131072,
			maxCompletionToken: 8192,
			type: "text-completion",
		},
		{
			id: "@cf/meta/llama-3.2-11b-vision-instruct",
			owner: "Meta",
			contextWindowToken: 131072,
			maxCompletionToken: 8192,
			type: "text-completion",
		},
		{
			id: "@cf/meta/llama-3.1-70b-instruct-fp8-fast",
			owner: "Meta",
			contextWindowToken: 131072,
			maxCompletionToken: 8192,
			type: "text-completion",
		},
		{
			id: "@cf/meta/llama-3.3-70b-instruct-fp8-fast",
			owner: "Meta",
			contextWindowToken: 131072,
			maxCompletionToken: 8192,
			type: "text-completion",
		},
		{
			id: "@cf/deepseek-ai/deepseek-r1-distill-qwen-32b",
			owner: "DeepSeek",
			contextWindowToken: 131072,
			maxCompletionToken: 8192,
			type: "text-completion",
		},
		{
			id: "@cf/mistral/mistral-7b-instruct-v0.1",
			owner: "Mistral",
			contextWindowToken: 32768,
			maxCompletionToken: 8192,
			type: "text-completion",
		},
		{
			id: "@cf/mistralai/mistral-small-3.1-24b-instruct",
			owner: "Mistral",
			contextWindowToken: 131072,
			maxCompletionToken: 8192,
			type: "text-completion",
		},
		{
			id: "@cf/meta/llama-3.1-8b-instruct",
			owner: "Meta",
			contextWindowToken: 131072,
			maxCompletionToken: 8192,
			type: "text-completion",
		},
		{
			id: "@cf/meta/llama-3.1-8b-instruct-fp8",
			owner: "Meta",
			contextWindowToken: 131072,
			maxCompletionToken: 8192,
			type: "text-completion",
		},
		{
			id: "@cf/meta/llama-3.1-8b-instruct-awq",
			owner: "Meta",
			contextWindowToken: 131072,
			maxCompletionToken: 8192,
			type: "text-completion",
		},
		{
			id: "@cf/meta/llama-3-8b-instruct",
			owner: "Meta",
			contextWindowToken: 8192,
			maxCompletionToken: 8192,
			type: "text-completion",
		},
		{
			id: "@cf/meta/llama-3-8b-instruct-awq",
			owner: "Meta",
			contextWindowToken: 8192,
			maxCompletionToken: 8192,
			type: "text-completion",
		},
		{
			id: "@cf/meta/llama-2-7b-chat-fp16",
			owner: "Meta",
			contextWindowToken: 4096,
			maxCompletionToken: 4096,
			type: "text-completion",
		},
		{
			id: "@cf/meta/llama-guard-3-8b",
			owner: "Meta",
			contextWindowToken: 131072,
			maxCompletionToken: 8192,
			type: "text-completion",
		},
		{
			id: "@cf/meta/llama-4-scout-17b-16e-instruct",
			owner: "Meta",
			contextWindowToken: 131072,
			maxCompletionToken: 8192,
			type: "text-completion",
		},
		{
			id: "@cf/google/gemma-3-12b-it",
			owner: "Google",
			contextWindowToken: 131072,
			maxCompletionToken: 8192,
			type: "text-completion",
		},
		{
			id: "@cf/qwen/qwq-32b",
			owner: "Qwen",
			contextWindowToken: 131072,
			maxCompletionToken: 8192,
			type: "text-completion",
		},
		{
			id: "@cf/qwen/qwen2.5-coder-32b-instruct",
			owner: "Qwen",
			contextWindowToken: 131072,
			maxCompletionToken: 8192,
			type: "text-completion",
		},
		{
			id: "@cf/qwen/qwen3-30b-a3b-fp8",
			owner: "Qwen",
			contextWindowToken: 131072,
			maxCompletionToken: 8192,
			type: "text-completion",
		},
		{
			id: "@cf/openai/gpt-oss-120b",
			owner: "OpenAI",
			contextWindowToken: 128000,
			maxCompletionToken: 16384,
			type: "text-completion",
		},
		{
			id: "@cf/openai/gpt-oss-20b",
			owner: "OpenAI",
			contextWindowToken: 128000,
			maxCompletionToken: 16384,
			type: "text-completion",
		},
		{
			id: "@cf/aisingapore/gemma-sea-lion-v4-27b-it",
			owner: "AI Singapore",
			contextWindowToken: 131072,
			maxCompletionToken: 8192,
			type: "text-completion",
		},
		{
			id: "@cf/ibm-granite/granite-4.0-h-micro",
			owner: "IBM",
			contextWindowToken: 128000,
			maxCompletionToken: 8192,
			type: "text-completion",
		},
		{
			id: "@cf/zai-org/glm-4.7-flash",
			owner: "Zhipu AI",
			contextWindowToken: 128000,
			maxCompletionToken: 8192,
			type: "text-completion",
		},
		{
			id: "@cf/nvidia/nemotron-3-120b-a12b",
			owner: "Nvidia",
			contextWindowToken: 128000,
			maxCompletionToken: 8192,
			type: "text-completion",
		},
		{
			id: "@cf/moonshotai/kimi-k2.5",
			owner: "Moonshot AI",
			contextWindowToken: 200000,
			maxCompletionToken: 8192,
			type: "text-completion",
		},
		{
			id: "@cf/moonshotai/kimi-k2.6",
			owner: "Moonshot AI",
			contextWindowToken: 200000,
			maxCompletionToken: 8192,
			type: "text-completion",
		},
		{
			id: "@cf/google/gemma-4-26b-a4b-it",
			owner: "Google",
			contextWindowToken: 131072,
			maxCompletionToken: 8192,
			type: "text-completion",
		},

		// Image Models
		{
			id: "@cf/black-forest-labs/flux-1-schnell",
			owner: "Black Forest Labs",
			contextWindowToken: 0,
			maxCompletionToken: 1,
			type: "image-generation",
		},
		{
			id: "@cf/leonardo/lucid-origin",
			owner: "Leonardo",
			contextWindowToken: 0,
			maxCompletionToken: 1,
			type: "image-generation",
		},
		{
			id: "@cf/leonardo/phoenix-1.0",
			owner: "Leonardo",
			contextWindowToken: 0,
			maxCompletionToken: 1,
			type: "image-generation",
		},
		{
			id: "@cf/black-forest-labs/flux-2-dev",
			owner: "Black Forest Labs",
			contextWindowToken: 0,
			maxCompletionToken: 1,
			type: "image-generation",
		},
		{
			id: "@cf/black-forest-labs/flux-2-klein-4b",
			owner: "Black Forest Labs",
			contextWindowToken: 0,
			maxCompletionToken: 1,
			type: "image-generation",
		},
		{
			id: "@cf/black-forest-labs/flux-2-klein-9b",
			owner: "Black Forest Labs",
			contextWindowToken: 0,
			maxCompletionToken: 1,
			type: "image-generation",
		},

		// Audio Models
		{
			id: "@cf/openai/whisper",
			owner: "OpenAI",
			contextWindowToken: 4096,
			maxCompletionToken: 0,
			type: "audio-generation",
		},
		{
			id: "@cf/openai/whisper-large-v3-turbo",
			owner: "OpenAI",
			contextWindowToken: 4096,
			maxCompletionToken: 0,
			type: "audio-generation",
		},
		{
			id: "@cf/myshell-ai/melotts",
			owner: "MyShell",
			contextWindowToken: 4096,
			maxCompletionToken: 0,
			type: "audio-generation",
		},
		{
			id: "@cf/deepgram/aura-1",
			owner: "Deepgram",
			contextWindowToken: 4096,
			maxCompletionToken: 0,
			type: "audio-generation",
		},
		{
			id: "@cf/deepgram/nova-3",
			owner: "Deepgram",
			contextWindowToken: 4096,
			maxCompletionToken: 0,
			type: "audio-generation",
		},
		{
			id: "@cf/deepgram/nova-3 (WebSocket)",
			owner: "Deepgram",
			contextWindowToken: 4096,
			maxCompletionToken: 0,
			type: "audio-generation",
		},
		{
			id: "@cf/pipecat-ai/smart-turn-v2",
			owner: "Pipecat",
			contextWindowToken: 4096,
			maxCompletionToken: 0,
			type: "audio-generation",
		},
		{
			id: "@cf/deepgram/aura-2-en",
			owner: "Deepgram",
			contextWindowToken: 4096,
			maxCompletionToken: 0,
			type: "audio-generation",
		},
		{
			id: "@cf/deepgram/aura-2-es",
			owner: "Deepgram",
			contextWindowToken: 4096,
			maxCompletionToken: 0,
			type: "audio-generation",
		},
		{
			id: "@cf/deepgram/flux (WebSocket)",
			owner: "Deepgram",
			contextWindowToken: 4096,
			maxCompletionToken: 0,
			type: "audio-generation",
		},
	],
	gemini: [
		{
			id: "gemini-2.5-pro",
			owner: "Google",
			contextWindowToken: 2000000,
			maxCompletionToken: 8192,
			type: "text-completion",
		},
		{
			id: "gemini-2.5-flash",
			owner: "Google",
			contextWindowToken: 1000000,
			maxCompletionToken: 8192,
			type: "text-completion",
		},
		{
			id: "imagen-3.0-generate-002",
			owner: "Google",
			contextWindowToken: 0,
			maxCompletionToken: 1,
			type: "image-generation",
		},
	],
	anthropic: [
		{
			id: "claude-opus-4-7",
			owner: "Anthropic",
			contextWindowToken: 1000000,
			maxCompletionToken: 128000,
			type: "text-completion",
		},
		{
			id: "claude-sonnet-4-6",
			owner: "Anthropic",
			contextWindowToken: 1000000,
			maxCompletionToken: 64000,
			type: "text-completion",
		},
		{
			id: "claude-haiku-4-5",
			owner: "Anthropic",
			contextWindowToken: 200000,
			maxCompletionToken: 64000,
			type: "text-completion",
		},
	],
	cerebras: [
		{
			id: "llama3.1-8b",
			owner: "Meta",
			contextWindowToken: 8192,
			maxCompletionToken: 8192,
			type: "text-completion",
		},
		{
			id: "llama3.1-70b",
			owner: "Meta",
			contextWindowToken: 8192,
			maxCompletionToken: 8192,
			type: "text-completion",
		},
		{
			id: "qwen-3-235b-a22b-instruct-2507",
			owner: "Meta",
			contextWindowToken: 100000,
			maxCompletionToken: 40000,
			type: "text-completion",
		},
	],
} as const satisfies Record<
	AiProvider,
	ReadonlyArray<{
		id: string;
		owner: string;
		created?: Date;
		contextWindowToken: number;
		maxCompletionToken: number;
		type?: AiProviderModelType;
	}>
>;
